"""Tests for core.approval_multi_review_cli -- the stdin/stdout JSON
adapter around core.approval_transition.validate_multi_review_transition.

main() is called directly with in-memory StringIO streams. No Supabase,
file, subprocess, network, AI-model, or other external access occurs
anywhere in this file; every input is a plain in-memory JSON object.

All current-record anchor timestamps (`requested_at`, `created_at`) are
fixed, safely-in-the-past UTC values -- never the real wall clock. No
`reviewed_at`/`now` timestamp is threaded through this CLI's envelope
(the multi-review transition-request contract has no such field, unlike
the Block 5 single-review contract), so a successful review decision's own
`decided_at` is generated by the validator's own existing real-clock
fallback -- exactly the "access no clock except through the validator's
existing behavior" boundary this CLI is required to respect. No test
below asserts an exact value for that generated timestamp; every
assertion is on exit code, status transitions, and field shape only,
which are unaffected by the real clock's exact reading.

Exactly six tests are defined below, per the Block 6 Step 7 specification.
"""

import copy
import json
from io import StringIO

from core import approval_multi_review_cli

INVESTIGATION_ID = "11111111-1111-4111-8111-111111111111"
APPROVAL_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"

REQUESTED_AT = "2026-08-01T10:00:00Z"
CREATED_AT = "2026-08-01T10:00:00Z"
REVIEW_DECIDED_AT = "2026-08-01T11:00:00Z"

REJECTION_REASON = "The proposed status change is not sufficiently supported."


def _multi_review_record(
    risk_level="high",
    required_approvals=2,
    status="pending",
    requested_by="analyst-jane",
    **overrides,
):
    record = {
        "id": APPROVAL_ID,
        "investigation_id": INVESTIGATION_ID,
        "action_type": "update_investigation_state",
        "action_payload": {"status": "closed"},
        "requested_by": requested_by,
        "requested_at": REQUESTED_AT,
        "status": status,
        "approved_by": None,
        "approved_at": None,
        "rejected_by": None,
        "rejected_at": None,
        "rejection_reason": None,
        "expires_at": None,
        "consumed_by": None,
        "consumed_at": None,
        "created_at": CREATED_AT,
        "risk_level": risk_level,
        "required_approvals": required_approvals,
    }
    record.update(overrides)
    return record


def _review(reviewer_identity, decision="approve", decided_at=None):
    return {
        "approval_id": APPROVAL_ID,
        "reviewer_identity": reviewer_identity,
        "reviewer_identity_normalized": reviewer_identity.strip().casefold(),
        "decision": decision,
        "decided_at": decided_at or REVIEW_DECIDED_AT,
    }


def _approve_request(reviewed_by="Security Reviewer"):
    return {"decision": "approve", "reviewed_by": reviewed_by}


def _reject_request(reviewed_by="Security Reviewer", rejection_reason=REJECTION_REASON):
    return {"decision": "reject", "reviewed_by": reviewed_by, "rejection_reason": rejection_reason}


def _envelope(current_record=None, existing_reviews=None, transition_request=None):
    return {
        "current_record": _multi_review_record() if current_record is None else current_record,
        "existing_reviews": [] if existing_reviews is None else existing_reviews,
        "transition_request": _approve_request() if transition_request is None else transition_request,
    }


def _run(raw_stdin_text):
    stdin = StringIO(raw_stdin_text)
    stdout = StringIO()
    stderr = StringIO()
    exit_code = approval_multi_review_cli.main(stdin=stdin, stdout=stdout, stderr=stderr)
    return exit_code, stdout.getvalue(), stderr.getvalue()


def test_001_one_review_pending_to_approved_succeeds():
    envelope = _envelope(
        current_record=_multi_review_record(risk_level="low", required_approvals=1, status="pending"),
        existing_reviews=[],
        transition_request=_approve_request(reviewed_by="Security Reviewer"),
    )
    exit_code, stdout, stderr = _run(json.dumps(envelope))

    assert exit_code == 0
    assert stderr == ""
    parsed = json.loads(stdout)
    assert parsed["from_status"] == "pending"
    assert parsed["to_status"] == "approved"
    assert parsed["required_approvals"] == 1
    assert parsed["approval_count_before"] == 0
    assert parsed["approval_count_after"] == 1
    assert set(parsed["set_fields"].keys()) == {"status", "approved_by", "approved_at"}
    assert parsed["set_fields"]["approved_by"] == "Security Reviewer"


def test_002_first_of_two_pending_to_partially_approved_succeeds():
    envelope = _envelope(
        current_record=_multi_review_record(risk_level="high", required_approvals=2, status="pending"),
        existing_reviews=[],
        transition_request=_approve_request(reviewed_by="Reviewer One"),
    )
    exit_code, stdout, stderr = _run(json.dumps(envelope))

    assert exit_code == 0
    assert stderr == ""
    parsed = json.loads(stdout)
    assert parsed["from_status"] == "pending"
    assert parsed["to_status"] == "partially_approved"
    assert parsed["required_approvals"] == 2
    assert parsed["approval_count_before"] == 0
    assert parsed["approval_count_after"] == 1
    assert set(parsed["set_fields"].keys()) == {"status"}
    assert parsed["set_fields"]["status"] == "partially_approved"


def test_003_second_distinct_reviewer_partially_approved_to_approved_succeeds():
    envelope = _envelope(
        current_record=_multi_review_record(
            risk_level="high", required_approvals=2, status="partially_approved"
        ),
        existing_reviews=[_review("Reviewer One", "approve")],
        transition_request=_approve_request(reviewed_by="Reviewer Two"),
    )
    exit_code, stdout, stderr = _run(json.dumps(envelope))

    assert exit_code == 0
    assert stderr == ""
    parsed = json.loads(stdout)
    assert parsed["from_status"] == "partially_approved"
    assert parsed["to_status"] == "approved"
    assert parsed["approval_count_before"] == 1
    assert parsed["approval_count_after"] == 2
    assert set(parsed["set_fields"].keys()) == {"status", "approved_by", "approved_at"}
    assert parsed["set_fields"]["approved_by"] == "Reviewer Two"


def test_004_duplicate_reviewer_and_requester_self_approval_fail_closed():
    # A reviewer who already recorded an approve review may not review again.
    duplicate_envelope = _envelope(
        current_record=_multi_review_record(
            risk_level="high", required_approvals=2, status="partially_approved"
        ),
        existing_reviews=[_review("Reviewer One", "approve")],
        transition_request=_approve_request(reviewed_by="Reviewer One"),
    )
    exit_code_dup, stdout_dup, _stderr_dup = _run(json.dumps(duplicate_envelope))
    assert exit_code_dup == 2
    assert stdout_dup == ""

    # The original requester may never approve their own request.
    self_approval_envelope = _envelope(
        current_record=_multi_review_record(
            risk_level="low", required_approvals=1, status="pending", requested_by="analyst-jane"
        ),
        existing_reviews=[],
        transition_request=_approve_request(reviewed_by="analyst-jane"),
    )
    exit_code_self, stdout_self, _stderr_self = _run(json.dumps(self_approval_envelope))
    assert exit_code_self == 2
    assert stdout_self == ""


def test_005_rejection_from_partially_approved_succeeds_while_terminal_states_reject_further_review():
    reject_envelope = _envelope(
        current_record=_multi_review_record(
            risk_level="high", required_approvals=2, status="partially_approved"
        ),
        existing_reviews=[_review("Reviewer One", "approve")],
        transition_request=_reject_request(reviewed_by="Reviewer Two"),
    )
    exit_code, stdout, stderr = _run(json.dumps(reject_envelope))

    assert exit_code == 0
    assert stderr == ""
    parsed = json.loads(stdout)
    assert parsed["from_status"] == "partially_approved"
    assert parsed["to_status"] == "rejected"
    assert set(parsed["set_fields"].keys()) == {"status", "rejected_by", "rejected_at", "rejection_reason"}

    # A terminal (already-approved) record rejects any further review.
    terminal_envelope = _envelope(
        current_record=_multi_review_record(
            risk_level="low",
            required_approvals=1,
            status="approved",
            approved_by="Security Reviewer",
            approved_at=REVIEW_DECIDED_AT,
        ),
        existing_reviews=[],
        transition_request=_approve_request(reviewed_by="Another Reviewer"),
    )
    exit_code_terminal, stdout_terminal, _stderr_terminal = _run(json.dumps(terminal_envelope))
    assert exit_code_terminal == 2
    assert stdout_terminal == ""


def test_006_malformed_input_fails_safely_inputs_unmodified_and_output_deterministic():
    for raw in ("", "{not valid json", "null", "[]"):
        exit_code, stdout, stderr = _run(raw)
        assert exit_code == 2
        assert stdout == ""
        assert "Traceback" not in stderr

    envelope = _envelope(
        current_record=_multi_review_record(risk_level="low", required_approvals=1, status="pending"),
        existing_reviews=[],
        transition_request=_approve_request(reviewed_by="Security Reviewer"),
    )
    snapshot = copy.deepcopy(envelope)

    exit_code, stdout, _stderr = _run(json.dumps(envelope))

    assert exit_code == 0
    assert envelope == snapshot

    parsed = json.loads(stdout)
    assert list(parsed.keys()) == sorted(parsed.keys())
    round_tripped = json.dumps(parsed, sort_keys=True, ensure_ascii=False) + "\n"
    assert round_tripped == stdout
