"""Focused tests for core.bug_bounty_finding_correlation -- the pure,
deterministic multi-tool finding correlator (Block 15G-CD).

No network, filesystem, environment-variable, subprocess, clock,
randomness, database/Supabase, MCP, or LLM/model access occurs anywhere
in this file. Every input is a plain in-memory mapping -- semantic
hints are supplied as already-produced data, never generated by calling
an LLM here.
"""

from __future__ import annotations

import pytest

from core.bug_bounty_evidence_normalization import EVIDENCE_REQUIRED_FIELDS
from core.bug_bounty_finding_correlation import (
    BugBountyFindingCorrelationError,
    correlate_bug_bounty_evidence,
)


def _record(**overrides):
    record = {field: None for field in EVIDENCE_REQUIRED_FIELDS}
    record.update({
        "evidence_id": "EV-0000000000000001",
        "source_tool": "http_assessor",
        "source_observation_id": "obs-1",
        "observation_type": "web_configuration",
        "host": "localhost",
        "port": 3000,
        "scheme": "http",
        "url": "http://localhost:3000/",
        "path": "/",
        "cve": [],
        "validation_state": "unvalidated",
        "scope_reference": "http://localhost:3000",
        "first_observed": "2026-08-14T00:00:00Z",
        "last_observed": "2026-08-14T00:00:00Z",
        "execution_performed": False,
        "evidence_digest": "sha256:" + "0" * 64,
    })
    record.update(overrides)
    return record


# ---------------------------------------------------------------------------
# Exact duplicate collapse
# ---------------------------------------------------------------------------


class TestExactDuplicate:
    def test_001_identical_digest_collapsed(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "1" * 64)
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "1" * 64)  # same digest, different id
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["duplicate_evidence_count"] == 1
        assert result["total_groups"] == 1

    def test_002_distinct_digests_not_collapsed(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "1" * 64)
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "2" * 64, path="/other", host="other-host")
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["duplicate_evidence_count"] == 0
        assert result["total_groups"] == 2


# ---------------------------------------------------------------------------
# Structural / fingerprint grouping (title-different, same vulnerability)
# ---------------------------------------------------------------------------


class TestFingerprintGrouping:
    def test_003_title_different_same_vulnerability_groups_together(self):
        # The real CSP example from this project's own live validation:
        # http_assessor's "Missing Content-Security-Policy header" vs
        # ZAP's "Content Security Policy (CSP) Header Not Set" -- wildly
        # different titles, same host/port/path/cwe.
        http_finding = _record(
            evidence_id="EV-http", evidence_digest="sha256:" + "3" * 64, source_tool="http_assessor",
            title="Missing Content-Security-Policy header", cwe="CWE-693", vulnerability_class="security_header_misconfiguration",
            technical_severity="medium", confidence="high",
        )
        zap_finding = _record(
            evidence_id="EV-zap", evidence_digest="sha256:" + "4" * 64, source_tool="zap",
            title="Content Security Policy (CSP) Header Not Set", cwe="CWE-693", vulnerability_class=None,
            technical_severity="medium", confidence="high",
        )
        result = correlate_bug_bounty_evidence(evidence_records=[http_finding, zap_finding])
        assert result["total_groups"] == 1
        group = result["groups"][0]
        assert set(group["member_evidence_ids"]) == {"EV-http", "EV-zap"}
        assert group["multi_tool_corroborated"] is True
        assert set(group["source_tools"]) == {"http_assessor", "zap"}

    def test_004_same_title_different_path_stays_separate(self):
        # Real example from this project's own live ZAP run: two
        # "Timestamp Disclosure - Unix" alerts with the same rule_id but
        # different paths must NOT be merged into one finding.
        first = _record(
            evidence_id="EV-t1", evidence_digest="sha256:" + "5" * 64, source_tool="zap",
            title="Timestamp Disclosure - Unix", cwe=None, path="/",
        )
        second = _record(
            evidence_id="EV-t2", evidence_digest="sha256:" + "6" * 64, source_tool="zap",
            title="Timestamp Disclosure - Unix", cwe=None, path="/robots.txt",
        )
        result = correlate_bug_bounty_evidence(evidence_records=[first, second])
        assert result["total_groups"] == 2

    def test_004b_colliding_evidence_id_with_distinct_digest_never_loses_a_member(self):
        # Regression test for a real bug this checkpoint's own live ZAP
        # validation discovered: core.bug_bounty_evidence_normalization
        # can (rarely, legitimately) hand back two distinct records that
        # happen to carry different evidence_id-derivation inputs but --
        # in the specific case being regression-tested here -- the same
        # evidence_id due to normalization's own content-digest design.
        # Correlation must group both as members of the same finding,
        # never silently keep only one.
        same_id_first = _record(
            evidence_id="EV-collide", evidence_digest="sha256:" + "aa" * 32, source_tool="zap",
            title="Timestamp Disclosure - Unix", cwe=None, path="/", sanitized_evidence="first evidence text",
        )
        same_id_second = _record(
            evidence_id="EV-collide", evidence_digest="sha256:" + "bb" * 32, source_tool="zap",
            title="Timestamp Disclosure - Unix", cwe=None, path="/", sanitized_evidence="second, different evidence text",
        )
        result = correlate_bug_bounty_evidence(evidence_records=[same_id_first, same_id_second])
        assert result["total_input_records"] == 2
        assert result["duplicate_evidence_count"] == 0  # digests differ -- not exact duplicates
        assert result["total_groups"] == 1
        assert len(result["groups"][0]["member_evidence_ids"]) == 2

    def test_005_never_deduplicates_on_title_string_alone(self):
        # Same title, different host -- must not group merely on title.
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "7" * 64, title="Same Title", host="host-a", cwe="CWE-1")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "8" * 64, title="Same Title", host="host-b", cwe="CWE-1")
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["total_groups"] == 2

    def test_006_open_port_and_missing_csp_are_not_the_same_finding(self):
        port_obs = _record(
            evidence_id="EV-port", evidence_digest="sha256:" + "9" * 64, source_tool="nmap",
            observation_type="service", cwe=None, vulnerability_class=None, path=None, port=3000,
        )
        csp_finding = _record(
            evidence_id="EV-csp", evidence_digest="sha256:" + "a" * 64, source_tool="http_assessor",
            observation_type="web_configuration", cwe="CWE-693", path="/", port=3000,
        )
        result = correlate_bug_bounty_evidence(evidence_records=[port_obs, csp_finding])
        assert result["total_groups"] == 2


# ---------------------------------------------------------------------------
# CVE-based grouping
# ---------------------------------------------------------------------------


class TestCveGrouping:
    def test_007_shared_cve_forces_grouping_despite_differing_path(self):
        a = _record(
            evidence_id="EV-cve-a", evidence_digest="sha256:" + "b" * 64, source_tool="nuclei",
            cve=["CVE-2021-9999"], path="/admin", cwe=None,
        )
        b = _record(
            evidence_id="EV-cve-b", evidence_digest="sha256:" + "c" * 64, source_tool="burp_dast",
            cve=["CVE-2021-9999"], path="/different-path", cwe=None,
        )
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["total_groups"] == 1
        assert result["groups"][0]["cve"] == ["CVE-2021-9999"]

    def test_008_no_shared_cve_no_forced_grouping(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "d" * 64, cve=["CVE-1111"], path="/x")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "e" * 64, cve=["CVE-2222"], path="/y")
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["total_groups"] == 2


# ---------------------------------------------------------------------------
# Informational vs. canonical separation
# ---------------------------------------------------------------------------


class TestInformationalSeparation:
    def test_009_bare_open_port_is_informational(self):
        record = _record(
            evidence_id="EV-port", evidence_digest="sha256:" + "f" * 64, source_tool="nmap",
            observation_type="service", technical_severity=None, vulnerability_class=None, cwe=None, cve=[],
        )
        result = correlate_bug_bounty_evidence(evidence_records=[record])
        assert result["groups"][0]["is_informational"] is True

    def test_010_finding_with_severity_is_not_informational(self):
        record = _record(
            evidence_id="EV-finding", evidence_digest="sha256:" + "1a" * 32, technical_severity="medium", cwe="CWE-693",
        )
        result = correlate_bug_bounty_evidence(evidence_records=[record])
        assert result["groups"][0]["is_informational"] is False

    def test_011_group_informational_only_if_every_member_qualifies(self):
        informational_member = _record(
            evidence_id="EV-info", evidence_digest="sha256:" + "1b" * 32, source_tool="nmap",
            technical_severity=None, vulnerability_class=None, cwe="CWE-693", cve=[], path="/",
        )
        real_member = _record(
            evidence_id="EV-real", evidence_digest="sha256:" + "1c" * 32, source_tool="zap",
            technical_severity="medium", cwe="CWE-693", path="/",
        )
        result = correlate_bug_bounty_evidence(evidence_records=[informational_member, real_member])
        assert result["total_groups"] == 1
        assert result["groups"][0]["is_informational"] is False  # one real member is enough


# ---------------------------------------------------------------------------
# Multi-tool confidence aggregation
# ---------------------------------------------------------------------------


class TestConfidenceAggregation:
    def test_012_single_tool_confidence_never_bumped(self):
        record = _record(evidence_id="EV-a", evidence_digest="sha256:" + "1d" * 32, confidence="medium", cwe="CWE-1")
        result = correlate_bug_bounty_evidence(evidence_records=[record])
        assert result["groups"][0]["aggregated_confidence"] == "medium"
        assert result["groups"][0]["multi_tool_corroborated"] is False

    def test_013_multi_tool_corroboration_bumps_confidence_one_level(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "1e" * 32, source_tool="http_assessor", confidence="medium", cwe="CWE-1", path="/")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "1f" * 32, source_tool="zap", confidence="medium", cwe="CWE-1", path="/")
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["groups"][0]["aggregated_confidence"] == "high"
        assert result["groups"][0]["corroboration_count"] == 2

    def test_014_confidence_bump_capped_at_high(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "20" * 32, source_tool="http_assessor", confidence="high", cwe="CWE-1", path="/")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "21" * 32, source_tool="zap", confidence="high", cwe="CWE-1", path="/")
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["groups"][0]["aggregated_confidence"] == "high"

    def test_015_same_tool_repeated_never_corroborates(self):
        # Two observations from the *same* tool about the same issue --
        # never treated as independent corroboration.
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "22" * 32, source_tool="nuclei", confidence=None, cwe="CWE-1", path="/", source_observation_id="t1")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "23" * 32, source_tool="nuclei", confidence=None, cwe="CWE-1", path="/", source_observation_id="t2")
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["groups"][0]["multi_tool_corroborated"] is False
        assert result["groups"][0]["corroboration_count"] == 1

    def test_016_severity_aggregated_as_highest_among_members(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "24" * 32, technical_severity="low", cwe="CWE-1", path="/")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "25" * 32, source_tool="zap", technical_severity="high", cwe="CWE-1", path="/")
        result = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert result["groups"][0]["aggregated_technical_severity"] == "high"


# ---------------------------------------------------------------------------
# Semantic hints
# ---------------------------------------------------------------------------


class TestSemanticHints:
    def test_017_same_finding_hint_merges_unmatched_pair(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "26" * 32, cwe=None, path="/a")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "27" * 32, cwe=None, path="/b")
        hints = [{"evidence_id_a": "EV-a", "evidence_id_b": "EV-b", "verdict": "same_finding", "rationale": "Same root cause, different observed paths."}]
        result = correlate_bug_bounty_evidence(evidence_records=[a, b], semantic_hints=hints)
        assert result["total_groups"] == 1

    def test_018_different_finding_hint_never_merges(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "28" * 32, cwe=None, path="/a")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "29" * 32, cwe=None, path="/b")
        hints = [{"evidence_id_a": "EV-a", "evidence_id_b": "EV-b", "verdict": "different_finding", "rationale": "Unrelated issues."}]
        result = correlate_bug_bounty_evidence(evidence_records=[a, b], semantic_hints=hints)
        assert result["total_groups"] == 2

    def test_019_uncertain_hint_does_not_merge_but_is_surfaced(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "2a" * 32, cwe=None, path="/a")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "2b" * 32, cwe=None, path="/b")
        hints = [{"evidence_id_a": "EV-a", "evidence_id_b": "EV-b", "verdict": "uncertain", "rationale": "Might be related, unclear."}]
        result = correlate_bug_bounty_evidence(evidence_records=[a, b], semantic_hints=hints)
        assert result["total_groups"] == 2
        assert len(result["uncertain_correlations"]) == 1
        assert result["uncertain_correlations"][0]["evidence_id_a"] == "EV-a"

    def test_020_hint_cannot_split_already_grouped_pair(self):
        # Deterministic fingerprint grouping wins -- a hint has no
        # split/undo capability at all in this API.
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "2c" * 32, cwe="CWE-1", path="/")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "2d" * 32, source_tool="zap", cwe="CWE-1", path="/")
        hints = [{"evidence_id_a": "EV-a", "evidence_id_b": "EV-b", "verdict": "different_finding", "rationale": "Actually unrelated."}]
        result = correlate_bug_bounty_evidence(evidence_records=[a, b], semantic_hints=hints)
        assert result["total_groups"] == 1  # still grouped -- hint cannot un-merge

    def test_021_unknown_evidence_id_in_hint_raises(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "2e" * 32)
        hints = [{"evidence_id_a": "EV-a", "evidence_id_b": "EV-nonexistent", "verdict": "same_finding", "rationale": "x"}]
        with pytest.raises(BugBountyFindingCorrelationError):
            correlate_bug_bounty_evidence(evidence_records=[a], semantic_hints=hints)

    def test_022_invalid_verdict_raises(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "2f" * 32)
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "30" * 32)
        hints = [{"evidence_id_a": "EV-a", "evidence_id_b": "EV-b", "verdict": "definitely_yes", "rationale": "x"}]
        with pytest.raises(BugBountyFindingCorrelationError):
            correlate_bug_bounty_evidence(evidence_records=[a, b], semantic_hints=hints)

    def test_023_blank_rationale_raises(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "31" * 32)
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "32" * 32)
        hints = [{"evidence_id_a": "EV-a", "evidence_id_b": "EV-b", "verdict": "same_finding", "rationale": "  "}]
        with pytest.raises(BugBountyFindingCorrelationError):
            correlate_bug_bounty_evidence(evidence_records=[a, b], semantic_hints=hints)

    def test_024_no_hints_supplied_is_fine(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "33" * 32)
        result = correlate_bug_bounty_evidence(evidence_records=[a])
        assert result["uncertain_correlations"] == []


# ---------------------------------------------------------------------------
# Evidence preservation / output contract / determinism
# ---------------------------------------------------------------------------


class TestEvidencePreservationAndContract:
    def test_025_every_evidence_source_preserved_in_group(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "34" * 32, source_tool="http_assessor", cwe="CWE-1", path="/")
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "35" * 32, source_tool="zap", cwe="CWE-1", path="/")
        c = _record(evidence_id="EV-c", evidence_digest="sha256:" + "36" * 32, source_tool="nuclei", cwe="CWE-1", path="/")
        result = correlate_bug_bounty_evidence(evidence_records=[a, b, c])
        group = result["groups"][0]
        assert set(group["member_evidence_ids"]) == {"EV-a", "EV-b", "EV-c"}
        assert set(group["source_tools"]) == {"http_assessor", "nuclei", "zap"}

    def test_026_exact_output_contract_fields(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "37" * 32)
        result = correlate_bug_bounty_evidence(evidence_records=[a])
        assert set(result.keys()) == {
            "correlation_version", "groups", "duplicate_evidence_count", "uncertain_correlations",
            "total_input_records", "total_groups", "execution_performed",
        }

    def test_027_execution_performed_always_false(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "38" * 32)
        result = correlate_bug_bounty_evidence(evidence_records=[a])
        assert result["execution_performed"] is False

    def test_028_deterministic_given_same_input(self):
        a = _record(evidence_id="EV-a", evidence_digest="sha256:" + "39" * 32)
        b = _record(evidence_id="EV-b", evidence_digest="sha256:" + "3a" * 32, host="other")
        first = correlate_bug_bounty_evidence(evidence_records=[a, b])
        second = correlate_bug_bounty_evidence(evidence_records=[a, b])
        assert first == second

    def test_029_input_never_mutated(self):
        import copy
        records = [_record(evidence_id="EV-a", evidence_digest="sha256:" + "3b" * 32)]
        snapshot = copy.deepcopy(records)
        correlate_bug_bounty_evidence(evidence_records=records)
        assert records == snapshot

    def test_030_empty_input_yields_empty_groups(self):
        result = correlate_bug_bounty_evidence(evidence_records=[])
        assert result["groups"] == []
        assert result["total_groups"] == 0
        assert result["total_input_records"] == 0


# ---------------------------------------------------------------------------
# End-to-end: real normalize_bug_bounty_evidence() output, not hand-built
# _record() fixtures -- this is the layer that actually caught the real
# defect (test_003 above already asserted correlation's own merge logic
# was correct using an overly-generous hand-built zap record with
# path="/"; it never exercised the real adapter's bare-origin-URL shape,
# which is what normalization actually receives).
# ---------------------------------------------------------------------------


class TestRealNormalizationIntegration:
    @staticmethod
    def _http_csp_result():
        return {
            "assessment_version": "1", "target": "http://juice-shop:3000/", "testing_profile": "safe_active",
            "findings": [{
                "finding_id": "BB15A-http-csp", "target": "http://juice-shop:3000/", "affected_path": "/",
                "affected_parameter": None, "title": "Missing Content-Security-Policy header",
                "finding_status": "validated", "vulnerability_class": "security_header_misconfiguration",
                "owasp_category": "A05:2021 Security Misconfiguration", "cwe": "CWE-693",
                "technical_severity": "medium", "confidence": "high",
                "evidence": [{
                    "method": "GET", "scoped_url": "http://juice-shop:3000/", "status_code": 200,
                    "observation": "Response did not include a Content-Security-Policy header.",
                    "evidence_digest": "sha256:" + "1" * 64,
                }],
                "validation": {"method": "deterministic_header_presence_check", "confirmed": True},
            }],
        }

    @staticmethod
    def _zap_csp_result():
        # Shaped exactly like the real adapters/bug_bounty_zap.py output
        # for a site-wide alert: url has no trailing slash, path is
        # already None (the adapter's own urlsplit(...).path or None),
        # vulnerability_class absent entirely.
        return {
            "tool_result_version": "1", "tool_id": "zap", "request_id": "REQ-1", "target": "http://juice-shop:3000",
            "status": "completed", "capability": "passive_only",
            "observations": [{
                "tool_id": "zap", "observation_type": "dast_observation", "rule_id": "10038",
                "title": "Content Security Policy (CSP) Header Not Set", "risk": "Medium", "confidence": "High",
                "url": "http://juice-shop:3000", "path": None, "parameter": None, "method": "GET",
                "cwe": "CWE-693", "owasp_category": None, "evidence_reference": "zap_alert_sha256:" + "2" * 64,
                "sanitized_evidence": None,
            }],
            "execution_performed": True,
        }

    def test_031_real_http_and_zap_csp_output_correlates_into_one_group(self):
        from core.bug_bounty_evidence_normalization import normalize_bug_bounty_evidence

        records = normalize_bug_bounty_evidence(
            source_results=[
                {"source_tool": "http_assessor", "result": self._http_csp_result()},
                {"source_tool": "zap", "result": self._zap_csp_result()},
            ],
            scope_reference="http://juice-shop:3000", observed_at="2026-08-15T00:00:00Z",
        )
        assert len(records) == 2
        result = correlate_bug_bounty_evidence(evidence_records=records)
        assert result["total_groups"] == 1
        group = result["groups"][0]
        assert group["multi_tool_corroborated"] is True
        assert set(group["source_tools"]) == {"http_assessor", "zap"}

    def test_032_both_tools_evidence_preserved_after_real_merge(self):
        from core.bug_bounty_evidence_normalization import normalize_bug_bounty_evidence

        records = normalize_bug_bounty_evidence(
            source_results=[
                {"source_tool": "http_assessor", "result": self._http_csp_result()},
                {"source_tool": "zap", "result": self._zap_csp_result()},
            ],
            scope_reference="http://juice-shop:3000", observed_at="2026-08-15T00:00:00Z",
        )
        result = correlate_bug_bounty_evidence(evidence_records=records)
        group = result["groups"][0]
        assert len(group["member_evidence_ids"]) == 2
        # Neither tool's own evidence_id was dropped in the merge.
        real_ids = {r["evidence_id"] for r in records}
        assert set(group["member_evidence_ids"]) == real_ids

    def test_033_real_cors_pair_correctly_stays_separate_different_cwe(self):
        # http_assessor's own CORS finding uses CWE-942; ZAP's real
        # "Cross-Domain Misconfiguration" alert uses CWE-264 -- a
        # genuinely different, broader classification. Structured
        # evidence does not establish equivalence, so this must NOT
        # merge, even after the path fix removes the other obstacle.
        from core.bug_bounty_evidence_normalization import normalize_bug_bounty_evidence

        http_cors_result = {
            "assessment_version": "1", "target": "http://juice-shop:3000/", "testing_profile": "safe_active",
            "findings": [{
                "finding_id": "BB15A-http-cors", "target": "http://juice-shop:3000/", "affected_path": "/",
                "affected_parameter": None, "title": "Notable CORS response headers observed",
                "finding_status": "validated", "vulnerability_class": "cors_misconfiguration",
                "owasp_category": "A05:2021 Security Misconfiguration", "cwe": "CWE-942",
                "technical_severity": "low", "confidence": "medium",
                "evidence": [{
                    "method": "OPTIONS", "scoped_url": "http://juice-shop:3000/", "status_code": 200,
                    "observation": "Access-Control-Allow-Origin: *", "evidence_digest": "sha256:" + "3" * 64,
                }],
                "validation": {"method": "deterministic_header_presence_check", "confirmed": False},
            }],
        }
        zap_cross_domain_result = {
            "tool_result_version": "1", "tool_id": "zap", "request_id": "REQ-1", "target": "http://juice-shop:3000",
            "status": "completed", "capability": "passive_only",
            "observations": [{
                "tool_id": "zap", "observation_type": "dast_observation", "rule_id": "10098",
                "title": "Cross-Domain Misconfiguration", "risk": "Medium", "confidence": "Medium",
                "url": "http://juice-shop:3000", "path": None, "parameter": None, "method": "GET",
                "cwe": "CWE-264", "owasp_category": None, "evidence_reference": "zap_alert_sha256:" + "4" * 64,
                "sanitized_evidence": "Access-Control-Allow-Origin: *",
            }],
            "execution_performed": True,
        }
        records = normalize_bug_bounty_evidence(
            source_results=[
                {"source_tool": "http_assessor", "result": http_cors_result},
                {"source_tool": "zap", "result": zap_cross_domain_result},
            ],
            scope_reference="http://juice-shop:3000", observed_at="2026-08-15T00:00:00Z",
        )
        result = correlate_bug_bounty_evidence(evidence_records=records)
        # Different CWE (CWE-942 vs CWE-264) -> different category ->
        # different fingerprint, even though path now matches on both.
        assert result["total_groups"] == 2
        assert result["groups"][0]["multi_tool_corroborated"] is False
        assert result["groups"][1]["multi_tool_corroborated"] is False

    def test_034_real_nmap_and_zap_informational_observations_stay_informational(self):
        # Regression guard for the fix: an informational observation
        # (no cwe/vulnerability_class/severity) must not accidentally
        # gain one of the two new fixed fields and get promoted into a
        # vulnerability finding.
        from core.bug_bounty_evidence_normalization import normalize_bug_bounty_evidence

        nmap_result = {
            "tool_result_version": "1", "tool_id": "nmap", "request_id": "REQ-1", "target": "juice-shop",
            "status": "completed",
            "observations": [{"type": "service", "port": 3000, "protocol": "tcp", "state": "open", "service": "ppp", "product": None, "version": None}],
            "evidence_references": ["nmap_xml_sha256:" + "5" * 64],
            "execution_performed": True,
        }
        zap_modern_webapp_result = {
            "tool_result_version": "1", "tool_id": "zap", "request_id": "REQ-1", "target": "http://juice-shop:3000",
            "status": "completed", "capability": "passive_only",
            "observations": [{
                "tool_id": "zap", "observation_type": "dast_observation", "rule_id": "10109",
                "title": "Modern Web Application", "risk": "Informational", "confidence": "Medium",
                "url": "http://juice-shop:3000", "path": None, "parameter": None, "method": "GET",
                "cwe": None, "owasp_category": None, "evidence_reference": "zap_alert_sha256:" + "6" * 64,
                "sanitized_evidence": None,
            }],
            "execution_performed": True,
        }
        records = normalize_bug_bounty_evidence(
            source_results=[
                {"source_tool": "nmap", "result": nmap_result},
                {"source_tool": "zap", "result": zap_modern_webapp_result},
            ],
            scope_reference="http://juice-shop:3000", observed_at="2026-08-15T00:00:00Z",
        )
        # The generic "dast_observation" fallback must not have been
        # applied here in a way that fabricates a severity -- it's still
        # informational because technical_severity/cwe/cve stay unset.
        zap_record = next(r for r in records if r["source_tool"] == "zap")
        assert zap_record["vulnerability_class"] == "dast_observation"
        result = correlate_bug_bounty_evidence(evidence_records=records)
        for group in result["groups"]:
            assert group["is_informational"] is True

    def test_035_same_cve_from_nuclei_and_nmap_merges_despite_differing_path(self):
        # A shared CVE is a stronger signal than the fingerprint (host/
        # port/path/category) -- real nuclei-shaped + nmap-shaped raw
        # results, run through the real normalizer, confirm this holds
        # for a genuinely cross-tool CVE match (Nuclei Reliability Step 1
        # regression coverage, not a hand-built fixture).
        from core.bug_bounty_evidence_normalization import normalize_bug_bounty_evidence

        nuclei_result = {
            "tool_result_version": "2", "tool_id": "nuclei", "request_id": "REQ-1", "target": "http://juice-shop:3000",
            "status": "completed",
            "observations": [{
                "type": "known_pattern_match", "template_id": "CVE-2023-9999", "title": "Vulnerable Component",
                "severity": "high", "target": "http://juice-shop:3000/app",
                "matcher": "version-match", "classification": {"cve_id": ["CVE-2023-9999"], "cwe_id": None},
            }],
            "evidence_references": ["nuclei_jsonl_sha256:" + "a" * 64], "execution_performed": True,
        }
        nmap_result = {
            "tool_result_version": "1", "tool_id": "nmap", "request_id": "REQ-1", "target": "juice-shop",
            "status": "completed",
            "observations": [{"type": "service", "port": 8080, "protocol": "tcp", "state": "open", "service": "http", "product": "widget-server", "version": "1.2"}],
            "evidence_references": ["nmap_xml_sha256:" + "b" * 64], "execution_performed": True,
        }
        records = normalize_bug_bounty_evidence(
            source_results=[
                {"source_tool": "nuclei", "result": nuclei_result},
                {"source_tool": "nmap", "result": nmap_result},
            ],
            scope_reference="http://juice-shop:3000", observed_at="2026-08-15T00:00:00Z",
        )
        # Force the CVE onto the nmap-shaped record too, the way a real
        # future correlation-input enrichment might supply it -- nmap's
        # own normalizer never sets `cve` itself, confirming this test
        # is exercising the correlation-level CVE-merge rule, not
        # accidentally relying on normalization inventing a CVE for nmap.
        assert records[1]["cve"] == []
        records[1] = dict(records[1], cve=["CVE-2023-9999"])
        result = correlate_bug_bounty_evidence(evidence_records=records)
        assert result["total_groups"] == 1
        assert result["groups"][0]["cve"] == ["CVE-2023-9999"]

    def test_036_unrelated_nuclei_findings_stay_distinct(self):
        from core.bug_bounty_evidence_normalization import normalize_bug_bounty_evidence

        nuclei_result = {
            "tool_result_version": "2", "tool_id": "nuclei", "request_id": "REQ-1", "target": "http://juice-shop:3000",
            "status": "completed",
            "observations": [
                {
                    "type": "known_pattern_match", "template_id": "exposed-env-file", "title": "Exposed .env File",
                    "severity": "high", "target": "http://juice-shop:3000/.env", "matcher": "status-200",
                    "classification": None,
                },
                {
                    "type": "known_pattern_match", "template_id": "exposed-git-config", "title": "Exposed .git/config",
                    "severity": "medium", "target": "http://juice-shop:3000/.git/config", "matcher": "status-200",
                    "classification": None,
                },
            ],
            "evidence_references": ["nuclei_jsonl_sha256:" + "c" * 64], "execution_performed": True,
        }
        records = normalize_bug_bounty_evidence(
            source_results=[{"source_tool": "nuclei", "result": nuclei_result}],
            scope_reference="http://juice-shop:3000", observed_at="2026-08-15T00:00:00Z",
        )
        result = correlate_bug_bounty_evidence(evidence_records=records)
        # Different paths, no shared CVE, both fall back to the same
        # generic vulnerability_class -- but the fingerprint's path
        # component still keeps them genuinely separate.
        assert result["total_groups"] == 2

    def test_037_duplicate_exact_nuclei_output_collapses(self):
        from core.bug_bounty_evidence_normalization import normalize_bug_bounty_evidence

        one_observation = {
            "type": "known_pattern_match", "template_id": "exposed-env-file", "title": "Exposed .env File",
            "severity": "high", "target": "http://juice-shop:3000/.env", "matcher": "status-200", "classification": None,
        }
        nuclei_result = {
            "tool_result_version": "2", "tool_id": "nuclei", "request_id": "REQ-1", "target": "http://juice-shop:3000",
            "status": "completed",
            "observations": [dict(one_observation), dict(one_observation)],  # identical, duplicated
            "evidence_references": ["nuclei_jsonl_sha256:" + "d" * 64], "execution_performed": True,
        }
        records = normalize_bug_bounty_evidence(
            source_results=[{"source_tool": "nuclei", "result": nuclei_result}],
            scope_reference="http://juice-shop:3000", observed_at="2026-08-15T00:00:00Z",
        )
        result = correlate_bug_bounty_evidence(evidence_records=records)
        assert result["duplicate_evidence_count"] == 1
        assert result["total_groups"] == 1


# ---------------------------------------------------------------------------
# Structural validation
# ---------------------------------------------------------------------------


class TestStructuralValidation:
    def test_031_non_list_evidence_records_raises(self):
        with pytest.raises(BugBountyFindingCorrelationError):
            correlate_bug_bounty_evidence(evidence_records="not-a-list")

    def test_032_evidence_record_missing_field_raises(self):
        bad = _record(evidence_id="EV-a", evidence_digest="sha256:" + "3c" * 32)
        del bad["host"]
        with pytest.raises(BugBountyFindingCorrelationError):
            correlate_bug_bounty_evidence(evidence_records=[bad])

    def test_033_evidence_record_extra_field_raises(self):
        bad = _record(evidence_id="EV-a", evidence_digest="sha256:" + "3d" * 32)
        bad["unexpected"] = "x"
        with pytest.raises(BugBountyFindingCorrelationError):
            correlate_bug_bounty_evidence(evidence_records=[bad])

    def test_034_blank_evidence_id_raises(self):
        bad = _record(evidence_id="   ", evidence_digest="sha256:" + "3e" * 32)
        with pytest.raises(BugBountyFindingCorrelationError):
            correlate_bug_bounty_evidence(evidence_records=[bad])
