"""Pure orchestration for a bounded Purple Team remediation
recommendation boundary (Full Security Lifecycle checkpoint).

## Recommendation, never applied remediation

This module produces a *recommendation* only -- a deterministic summary
of what the earlier lifecycle stages (Threat Intel review, Threat Hunt
review, Detection Engineering, Red Validation) actually found, plus a
small set of closed, deterministic recommendation strings derived from
the canonical finding's own `remediation`/`detection_opportunity`
fields where present. It never edits a configuration, never deploys a
detection rule, never opens a ticket in an external system, and never
claims a retest occurred. `core.security_handoff.STAGE_OUTCOMES[
("purple_remediation", "recommendation")]` itself only ever allows
`"planned"`/`"needs_review"`/`"blocked"`/`"not_applicable"` -- there is
no `"applied"` outcome in that contract, and this module never invents
one.

`build_purple_remediation_recommendation` is this module's only public
function.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

RECOMMENDATION_VERSION = "1"


class PurpleRemediationError(ValueError):
    """Raised only for a structurally unusable `canonical_finding`
    argument to this module itself."""


def _validate_finding(value: Any) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise PurpleRemediationError("INVALID_FINDING: canonical_finding must be a mapping")
    finding_id = value.get("finding_id")
    if not isinstance(finding_id, str) or not finding_id.strip():
        raise PurpleRemediationError("INVALID_FINDING: canonical_finding['finding_id'] must be a non-blank string")
    return value


def build_purple_remediation_recommendation(
    *, canonical_finding: Any, ti_result: Any, hunt_result: Any, detection_result: Any, red_validation_result: Any,
) -> dict[str, Any]:
    """Deterministically build one remediation recommendation from a
    canonical finding and the already-computed results of the four
    earlier lifecycle stages. All five parameters are keyword-only and
    required. `canonical_finding` must be a mapping shaped at minimum
    like `core.bug_bounty_final_report`'s own canonical finding
    contract; the other four must each be a mapping (their own real
    stage-result shape from `core.bug_bounty_threat_intel_review`/
    `core.bug_bounty_threat_hunt_review`/this checkpoint's Detection
    Engineering result/Red Validation result) or `None` if that stage
    was never reached for this finding.

    Builds a bounded list of `recommendations` (each a short string),
    combining: the finding's own real `remediation` text when present;
    its own real `detection_opportunity` text when present and the
    detection stage produced no rule; a fixed telemetry-instrumentation
    recommendation when the hunt stage reported `"telemetry_gap"`; and a
    fixed manual-retest recommendation when Red Validation was
    unavailable. Every recommendation string is either copied verbatim
    from real upstream data or drawn from a small fixed set -- never
    generated by inspecting title text for keywords.

    Returns a new dict containing exactly `recommendation_version`
    (always `"1"`), `finding_id`, `recommendations` (list[str], never
    empty -- always includes at least one general retest-recommendation
    fallback when nothing more specific applies), `based_on` (a
    dict recording which upstream stage results were actually available
    when this recommendation was built: `{ti_reviewed, hunt_reviewed,
    detection_reviewed, red_validation_reviewed}`, each bool),
    `outcome` (always `"recommendation_created"`), `human_review_required`
    (always `True`), `execution_performed` (always `False` -- this is a
    recommendation only; no remediation was applied, no rule was
    deployed, no retest was performed).

    Raises `PurpleRemediationError` only for a structurally invalid
    `canonical_finding`.
    """
    validated = _validate_finding(canonical_finding)

    recommendations: list[str] = []

    remediation_text = validated.get("remediation")
    if isinstance(remediation_text, str) and remediation_text.strip():
        recommendations.append(remediation_text.strip())

    detection_produced_rule = isinstance(detection_result, Mapping) and detection_result.get("outcome") == "candidate_ready"
    detection_opportunity = validated.get("detection_opportunity")
    if not detection_produced_rule and isinstance(detection_opportunity, str) and detection_opportunity.strip():
        recommendations.append(detection_opportunity.strip())

    if isinstance(hunt_result, Mapping) and hunt_result.get("outcome") == "telemetry_gap":
        missing = hunt_result.get("missing_telemetry") or []
        if missing:
            recommendations.append(
                "Instrument the missing telemetry sources (" + ", ".join(str(m) for m in missing)
                + ") to make future hunting/detection for this finding class feasible.",
            )

    if isinstance(red_validation_result, Mapping) and red_validation_result.get("outcome") != "validated":
        recommendations.append(
            "Controlled/automated validation was not available in this environment -- "
            "recommend a manual retest by a human analyst before closing this finding.",
        )

    if not recommendations:
        recommendations.append(
            "No specific remediation guidance was available from upstream stages -- "
            "recommend manual analyst review of this finding.",
        )

    return {
        "recommendation_version": RECOMMENDATION_VERSION,
        "finding_id": validated["finding_id"],
        "recommendations": recommendations,
        "based_on": {
            "ti_reviewed": isinstance(ti_result, Mapping),
            "hunt_reviewed": isinstance(hunt_result, Mapping),
            "detection_reviewed": isinstance(detection_result, Mapping),
            "red_validation_reviewed": isinstance(red_validation_result, Mapping),
        },
        "outcome": "recommendation_created",
        "human_review_required": True,
        "execution_performed": False,
    }
